name: 'Compute Geode-solutions benchmarks'
description: 'Compute Geode-solutions benchmarks'
inputs:
  repository:
    description: 'Repository'
    required: true
  directory:
    description: 'Directory of tests'
    required: true
  token:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'

