name: 'Download GitHub Release'
description: 'Download Github Release'
inputs: 
  owner:
    description: 'GitHub owner name (user/organization)'
    default: 'Geode-solutions'
    requiered: false
  repository:
    description: 'GitHub repository name'
    required: true
  file:
    description: 'regex of the file to download'
    required: true
  version:
    description: 'Release version'
    requiered: false
  token:
    description: 'Github token'
    required: true
outputs:
  path:
    description: 'path of the extracted asset'
runs:
  using: 'node16'
  main: 'index.js'

