name: 'Download GitHub Release'
description: 'Download Github Release'
inputs: 
  owner:
    description: 'GitHub owner name (user/organization)'
    default: 'Geode-solutions'
    requiered: false
  repository:
    description: 'GitHub repository name'
    required: true
  token:
    description: 'Github token'
    required: true
runs:
  using: 'node16'
  main: 'index.js'

