name: "Install Python dependencies"

inputs:
  repos:
    type: string
  branch:
    type: string
  wheels:
    type: string
  use_registry:
    type: boolean
    required: true
  token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Geode-solutions/actions/get-release@master
      if: ${{ inputs.wheels == '' && inputs.use_registry == 'false' }}
      id: wheels
      with:
        repository: ${{ inputs.repos }}
        file: ".whl"
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
    - name: Get wheels
      id: result
      run: |
        if [ -n "${{ inputs.wheels }}" ]; then
          echo "wheels=${{ inputs.wheels }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.wheels.outputs.path }}" ]; then
          echo "wheels=${{ steps.wheels.outputs.path }}" >> $GITHUB_OUTPUT
        else
          echo "wheels=" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install OSMesa
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install libosmesa6-dev
      shell: bash
    - name: Install OSMesa
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install 7zip.install
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/25.2.1/mesa3d-25.2.1-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        echo "${{ github.workspace }}\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
    - name: Install dependencies
      run: |
        pip install --extra-index-url https://wheels.vtk.org .[cpu]
        wheels=$(echo "${{ steps.result.outputs.wheels }}" | sed 's/\;/\ /g')
        echo "all wheels = $wheels"
        if [ -n "$wheels" ]; then 
          # dev_wheels=$(echo "$wheels" | tr ' ' '\n' | grep '0\.0\.0' || echo "")
          dev_wheels="$wheels"
          echo "dev wheels = $dev_wheels"
          if [ -n "$dev_wheels" ]; then 
            filtered_wheels=$(echo "$dev_wheels" | tr '\n' ' ' | sed 's/ $//')
            echo "filtered wheels = $filtered_wheels"
            if [ -n "$filtered_wheels" ]; then 
              for wheel in $filtered_wheels; do
                pip install --extra-index-url https://wheels.vtk.org $wheel[cpu]
              done
            fi
          fi
        fi
        pip list
      shell: bash
