name: 'Doxyrest + Sphinx'
description: 'Doxyrest + Sphinx'
inputs:
  directory:
    description: 'Directory to build'
    default: 'build'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
