name: 'Generate doc'
description: 'Create documentation using clang-doc'
inputs:
  directory: 
    required: true
    default: '.'
  base_directory:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
