name: "Install microservices"
description: "Install microservices dependencies"

inputs:
  repos:
    type: string
    required: true
  branch:
    type: string
    required: true
  wheels:
    type: string
  microservices:
    type: string
    required: true
  use_registry:
    type: boolean
    required: true
  token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Geode-solutions/actions/get-release@master
      if: ${{ inputs.wheels == '' && inputs.use_registry == 'false' }}
      id: wheels
      with:
        repository: ${{ inputs.repos }}
        file: ".whl"
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
    - name: Get wheels
      id: result
      run: |
        if [ -n "${{ inputs.wheels }}" ]; then
          echo "wheels=${{ inputs.wheels }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.wheels.outputs.path }}" ]; then
          echo "wheels=${{ steps.wheels.outputs.path }}" >> $GITHUB_OUTPUT
        else
          echo "wheels=" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install OSMesa
      uses: Geode-solutions/actions/install/osmesa@master
    - name: Install microservices
      run: |
        bin_folder=$([[ ${{ runner.os }} == 'Windows' ]] && echo "Scripts" || echo "bin")
        find "${{ inputs.microservices }}" -mindepth 1 -maxdepth 1 -type d -print0 |
          xargs -0 -I{} -P 2 -n1 bash -c '
            set -euo pipefail            
            ms="{}"
            microservice="$GITHUB_WORKSPACE/$ms"
            echo "Processing: $microservice"
            cd "$microservice"
            python -m venv venv
            ./venv/$bin_folder/pip install --pre -r requirements.txt            
            wheels=$(echo "${{ steps.result.outputs.wheels }}" | sed "s/;/ /g")
            echo "wheels = $wheels"            
            if [ -n "$wheels" ]; then
              for wheel in $wheels; do
                ./venv/'"$bin_folder"'/pip install --pre "$wheel"
              done
            fi            
            ./venv/$bin_folder/pip list
            echo "Done: $microservice"
      shell: bash
