name: "Install microservices"

inputs:
  repos:
    type: string
    required: true
  branch:
    type: string
    required: true
  microservices_path:
    type: string
    required: true
  token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Geode-solutions/actions/get-release@master
      id: wheels
      with:
        repository: ${{ inputs.repos }}
        file: ".whl"
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
    - name: Install microservices
      run: |
        bin_folder=$([[ ${{ runner.os }} == 'Windows' ]] && echo "Scripts" || echo "bin")
        for microservice in ${{ inputs.microservices_path }}/*/; do
          microservice="$GITHUB_WORKSPACE/$microservice"
          echo "microservice = $microservice"
          if [ -d "$microservice" ]; then
            cd $microservice
            python -m venv venv
            venv/$bin_folder/pip install --extra-index-url https://wheels.vtk.org -r requirements.txt
            wheels=$(echo "${{ steps.wheels.outputs.path }}" | sed 's/\;/\ /g')
            echo "all wheels = $wheels"
            if [ -n "$wheels" ]; then 
              for wheel in $wheels; do
                venv/$bin_folder/pip install --extra-index-url https://wheels.vtk.org $wheel
              done
            fi
            venv/$bin_folder/pip list
          fi
        done
      shell: bash
