name: "Install microservices"
description: "Install microservices dependencies"

inputs:
  repos:
    type: string
    required: true
  branch:
    type: string
    required: true
  wheels:
    type: string
  microservices:
    type: string
    required: true
  use_registry:
    type: boolean
    required: true
  token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: DEBUG
      run: |
        pwd
        ls
      shell: bash
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - uses: Geode-solutions/actions/get-release@master
      if: ${{ inputs.wheels == '' && inputs.use_registry == 'false' }}
      id: wheels
      with:
        repository: ${{ inputs.repos }}
        file: "pyinstaller-${{ runner.os }}.zip"
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
    - name: Get wheels
      id: result
      run: |
        if [ -n "${{ inputs.wheels }}" ]; then
          echo "wheels=${{ inputs.wheels }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.wheels.outputs.path }}" ]; then
          echo "wheels=${{ steps.wheels.outputs.path }}" >> $GITHUB_OUTPUT
        else
          echo "wheels=" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install microservices
      run: |
        pwd
        ls
        IFS=';' read -ra paths <<< "${{ steps.result.outputs.wheels }}"
        for path in "${paths[@]}"; do
          echo "→ Trying to copy: $path"
          ls $path
          cp -v -- $path/* .
        done
      shell: bash
    - name: Install OSMesa
      uses: Geode-solutions/actions/install/osmesa@master
