name: 'Clang Format'
description: 'Format C++ code using clang-format'
inputs:
  user: 
    description: 'Who push'
    required: true
    default: 'BotellaA'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
