name: "Install OsMesa"

runs:
  using: "composite"
  steps:
    - name: Install OSMesa
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install libosmesa6-dev
      shell: bash
    - name: Install OSMesa
      if: ${{ runner.os == 'Windows' }}
      # uses: f3d-app/install-mesa-windows-action@v1
      # with:
      #   path: ${{github.workspace}}
      #   version: 25.0.7
      run: |
        choco install 7zip.install
        Invoke-WebRequest -Uri "https://github.com/pal1000/mesa-dist-win/releases/download/25.0.7/mesa3d-25.0.7-release-msvc.7z" -OutFile "mesa.7z"
        & "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        echo "${{ github.workspace }}\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
