name: "Install Node dependencies"

inputs:
  repos:
    type: string
    required: true
  branch:
    type: string
    required: true
  tarballs:
    type: string
  token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        registry-url: "https://registry.npmjs.org"
        node-version: 22
    - uses: Geode-solutions/actions/get-release@master
      if: ${{ inputs.tarballs == '' }}
      id: tarballs
      with:
        repository: ${{ inputs.repos }}
        file: ".tgz"
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
    - name: Get tarballs
      id: result
      run: |
        if [ -n "${{ inputs.tarballs }}" ]; then
          echo "tarballs=${{ inputs.tarballs }}" >> $GITHUB_OUTPUT
        else
          echo "tarballs=${{ steps.tarballs.outputs.path }}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Install dependencies
      run: |
        npm install
        tarballs=$(echo "${{ steps.result.outputs.tarballs }}" | sed 's/\;/\ /g')
        echo "Tarballs = $tarballs"
        if [ -n "$tarballs" ]; then
          npm install --no-save $tarballs
        fi
        npm list --depth=0 || true
      shell: bash
