name: 'Download GitHub Release'
description: 'Download Github Release'
inputs: 
  repository:
    description: 'GitHub repository name (ex: owner/repo, owner default value is Geode-solutions). You can provide a list of values separated by a ";" '
    required: true
  file:
    description: 'regex of the file to download'
    required: true
  token:
    description: 'Github token'
    required: true
outputs:
  path:
    description: 'path of the extracted asset'
runs:
  using: 'node16'
  main: 'index.js'

