name: 'Download GitHub Release'
description: 'Download Github Release'
inputs: 
  user:
    description: 'user/organization name'
    default: 'Geode-solutions'
    requiered: true
  repository:
    description: 'repository name'
    required: true
  file:
    description: 'regex of the file to download'
    required: true
  token:
    description: 'Github token'
    required: false
outputs:
  path:
    description: 'path of the extracted asset'
runs:
  using: 'node12'
  main: 'index.js'

