on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      repo:
        type: string
        default: ${{ github.repository }}
      extra:
        type: string
        default: ""
      config:
        type: string
        default: "Release"
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  run:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - {system: "win64", shared: "ON"}
        - {system: "win64-static", shared: "OFF"}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        token: ${{ secrets.TOKEN }}
    - uses: actions/cache/restore@v3
      with:
        path: build/third_party
        key: ${{ runner.os }}-${{ matrix.config.system }}-${{ hashFiles('cmake/**.cmake') }}
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ inputs.repos }}
        file: '-${{ matrix.config.system }}-private.zip'
        token: ${{ secrets.TOKEN }}
    - name: Generate package
      run: |
        choco install openssl -r --no-progress
        if(!$?) { exit 1 }
        if(!(test-path build)) { mkdir build }
        cd build
        $version = ${env:GITHUB_REF} -replace 'refs\/tags\/v', ''
        cmake ${{ inputs.extra }} -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS:BOOL=${{ matrix.config.shared }} -DCMAKE_PREFIX_PATH:PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_TESTS:BOOL=OFF -DINCLUDE_PYBIND11:BOOL=ON -DCPACK_PACKAGE_VERSION:STRING=$version -DCPACK_SYSTEM_NAME:STRING=${{ matrix.config.system }} ..
        cmake --build . --config ${{ inputs.config }} -j 2
        cd ${{ inputs.directory }}
        cpack -D CPACK_COMPONENTS_ALL="public;private" -C ${{ inputs.config }} .
        get-childitem *.zip | foreach { rename-item $_ $_.Name.Replace(".zip", "-private.zip") }
        cmake --build . --target PACKAGE --config ${{ inputs.config }}
    - name: Upload
      run: |
        Get-ChildItem -Path "build/${{ inputs.directory }}" -Filter *.zip | Foreach-Object { gh release upload --clobber --repo ${env:GITHUB_REPOSITORY} ${env:GITHUB_REF_NAME} $_.FullName }
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    - name: Notify slack
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
