on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    container: "ghcr.io/geode-solutions/centos:master"
    strategy:
      matrix:
        config:
        - {python: "3.7", tag: "cp37-cp37m"}
        - {python: "3.8", tag: "cp38-cp38"}
        - {python: "3.9", tag: "cp39-cp39"}
        - {python: "3.10", tag: "cp310-cp310"}
    steps:
    - uses: actions/checkout@v3
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ inputs.repos }}
        file: '-rhel-private.tar.gz'
        token: ${{ secrets.TOKEN }}
    - name: Compile
      run: |
        export PATH=/opt/python/${{ matrix.config.tag }}/bin:$PATH
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_PYTHON:BOOL=ON -DPYTHON_VERSION:STRING=${{ matrix.config.python }} ..
        cmake --build . -- -j2
        cd ${{ inputs.directory}}
        ctest --output-on-failure -R -py-
        cmake --build . --target wheel --config Debug
      env:
        GEODE_LICENSE_LOCATION: ${{ github.workspace }}/geode.lic
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
