on: 
  workflow_call:
    inputs:
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  run:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - {system: "win64", shared: "ON"}
        - {system: "win64-static", shared: "OFF"}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: build/third_party
        key: ${{ runner.os }}-${{ matrix.config.system }}-${{ hashFiles('cmake/**.cmake') }}
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ inputs.repos }}
        file: '-${{ matrix.config.system }}-private.zip'
        token: ${{ secrets.TOKEN }}
    - name: Libraries
      id: libraries
      run: |
        $old_path = "${{ steps.repos.outputs.path }}"
        $new_path = $old_path.replace(";", "\bin;")
        echo "path=$new_path\n" >> $GITHUB_OUTPUT
    - name: Compile & Test
      run: |
        choco install openssl -r --no-progress
        if(!$?) { exit 1 }
        if(!(test-path build)) { mkdir build }
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DBUILD_SHARED_LIBS:BOOL=${{ matrix.config.shared }} -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" ..
        cmake --build . --config Debug -j 2
        cd ${{ inputs.directory }}
        $paths = "${{ steps.libraries.outputs.path }}"
        echo $paths
        Foreach($path in $paths.split(";")){if(Test-Path -Path $path) {Copy-Item -Path $path\* -Destination bin\Debug}}
        dir bin\Debug
        ctest -C Debug --output-on-failure -j 2
      env:
        GEODE_LICENSE_LOCATION: ${{ github.workspace }}/geode.lic
    - name: Notify slack
      if: failure() && github.ref == 'refs/heads/master'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 
      
