on: 
  workflow_call:
    inputs:
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    container: "ghcr.io/geode-solutions/ubuntu:master"
    if: (github.event_name == 'pull_request' || github.ref == 'refs/heads/master')
    steps:
    - uses: actions/checkout@v3
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ inputs.repos }}
        file: '-ubuntu-private.tar.gz'
        token: ${{ secrets.TOKEN }}
    - name: Libraries
      id: libraries
      run: |
        new_path=$(echo "${{ steps.repos.outputs.path }}" | sed 's/\;/\/lib\:/g')
        echo "LD_LIBRARY_PATH=$new_path" >> $GITHUB_ENV
    - name: Compile
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" ..
        cmake --build . -- -j2
    - name: Kcov
      run: curl -s https://raw.githubusercontent.com/Geode-solutions/actions/master/kcov.sh | bash -s -- ${GITHUB_WORKSPACE}/build/${{ inputs.directory }}/bin
    - uses: codecov/codecov-action@v2
      with: 
        token: ${{ secrets.CODECOV_TOKEN }}
        file: kcov/kcov-merged/cobertura.xml
