on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel-if-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 8BitJonny/gh-get-current-pr@2.2.0
        id: PR
      - name: cancelling
        if: steps.PR.outputs.pr_found == 'true'
        uses: andymckay/cancel-action@0.3

  test-repository:
    needs: cancel-if-PR
    uses: Geode-solutions/actions/.github/workflows/cpp-test-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      light: ${{ github.ref_name != 'next' }}
    secrets: inherit

  trigger-deploy:
    needs: test-repository
    uses: Geode-solutions/actions/.github/workflows/trigger-deploy.yml@master
    secrets: inherit
