on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      branch:
        type: string
        default: "master"
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  test-repository:
    uses: Geode-solutions/actions/.github/workflows/cpp-test-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      light: true
      type: "Release"
      branch: ${{ inputs.branch }}
      wheels_from_pypi: true
    secrets: inherit

  notify:
    runs-on: ubuntu-latest
    if: ${{ always() && needs.test-repository.result == 'failure' }}
    needs: test-repository
    steps:
      - name: Notify slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
