on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ "$GITHUB_REF_NAME" == "master" || "$GITHUB_REF_NAME" == "next" ]]; then 
            exit 1
          fi
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            echo $$GITHUB_REF_NAME
            github.rest.actions.createWorkflowDispatch({
              owner: 'Geode-solutions',
              repo: 'Versions',
              workflow_id: 'cpp-merge-request.yml',
              ref: 'master',
              inputs: { branch: $GITHUB_REF_NAME }
            })