on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: "bindings/python"
    outputs:
      changes_detected:
        description: "commit has been done"
        value: ${{ jobs.prepare.outputs.changes_detected }}
    secrets:
      TOKEN:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: "pip-compile"
        run: |
          file=${{ inputs.directory }}/requirements.in
          if [ ! -f "$file" ]; then 
            exit 0
          fi
          pip install pip-tools
          echo $GITHUB_REF_NAME
          if [ $GITHUB_REF_NAME == "master" ]; then
            pip-compile -v --upgrade $file
          else
            pip-compile -v --pre --upgrade $file
          fi
          sed -i -E 's/==(.+)\.(.+)\.(.+)/==\1\.*,>=\1\.\2\.\3/' ${{ inputs.directory }}/requirements.txt
      - name: "Get config files"
        run: |
          curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.clang-format\?ref\=master > .clang-format
          curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.clang-tidy\?ref\=master > .clang-tidy
          curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.releaserc\?ref\=master > .releaserc
          curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/version.rc.in\?ref\=master > cmake/version.rc.in
      # - uses: DoozyX/clang-format-lint-action@master
      #   with:
      #     extensions: "h,cpp"
      #     clangFormatVersion: 16
      #     inplace: True
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: Apply prepare changes
