on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      repo:
        type: string
        default: ${{ github.repository }}
      version:
        type: string
        required: true
      prefix-release:
        type: string
        default: "v"
      upload-pypi:
        type: boolean
        default: true
      upload-gh:
        type: boolean
        default: false
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  release-linux:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-linux.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repo: ${{ inputs.repo }}
      repos: ${{ inputs.repos }}
      version: ${{ inputs.version }}
      prefix-release: ${{ inputs.prefix-release }}
    secrets: inherit

  release-linux-python:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-linux-python.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      version: ${{ inputs.version }}
      upload-pypi: ${{ inputs.upload-pypi }}
      upload-gh: ${{ inputs.upload-gh }}
    secrets: inherit

  release-windows:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-windows.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repo: ${{ inputs.repo }}
      repos: ${{ inputs.repos }}
      version: ${{ inputs.version }}
      prefix-release: ${{ inputs.prefix-release }}
    secrets: inherit

  release-windows-python:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-windows-python.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      version: ${{ inputs.version }}
      upload-pypi: ${{ inputs.upload-pypi }}
      upload-gh: ${{ inputs.upload-gh }}
    secrets: inherit

  public-release:
    if: github.ref == 'refs/heads/master'
    needs: [release-linux, release-windows]
    uses: Geode-solutions/actions/.github/workflows/cpp-public-release.yml@master
    secrets: inherit

  notify:
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-notify.yml@master
    needs:
      [
        release-linux,
        release-linux-python,
        release-windows,
        release-windows-python,
      ]
    secrets: inherit
