on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      python:
        type: boolean
        default: true
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  skip:
    uses: Geode-solutions/actions/.github/workflows/skip-pr.yml@master
    secrets: inherit

  test-repository:
    needs: skip
    if: needs.skip.outputs.pr_found == 'false'
    uses: Geode-solutions/actions/.github/workflows/cpp-test-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      light: ${{ github.ref_name != 'next' }}
      branch: ${{ github.ref_name }}
      python: ${{ inputs.python }}
    secrets: inherit
