on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      python:
        type: boolean
        default: true
    secrets:
      TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: Geode-solutions/actions/.github/workflows/cpp-prepare.yml@master
    secrets: inherit

  # tidy:
  #   needs: prepare
  #   runs-on: ubuntu-latest
  #   container: ghcr.io/geode-solutions/ubuntu:master
  #   steps:
  #     - uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   token: ${{ secrets.TOKEN }}
  #     - uses: actions/cache/restore@v4
  #       with:
  #         path: build/third_party
  #         key: ${{ runner.os }}-ubuntu-${{ hashFiles('cmake/Configure**.cmake') }}
  #     - uses: Geode-solutions/actions/get-release@master
  #       id: repos
  #       with:
  #         repository: ${{ inputs.repos }}
  #         file: "-ubuntu-private.tar.gz"
  #         token: ${{ secrets.TOKEN }}
  #         branch: ${{ github.event.pull_request.head.ref }}
  #     - name: Configure
  #       run: |
  #         mkdir -p build
  #         cd build
  #         cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" ..
  #         cmake --build . -t third_party -j 2
  #     - name: Tidy
  #       uses: ZedThree/clang-tidy-review@master
  #       with:
  #         build_dir: ${{ github.workspace }}/build/${{ inputs.directory }}
  #         clang_tidy_version: 17


  test-repository:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/cpp-test-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      light: ${{ github.event.pull_request.draft }}
      branch: ${{ github.event.pull_request.head.ref }}
      python: ${{ inputs.python }}
    secrets: inherit

  semantic-commit:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/semantic-commit.yml@master

  release:
    needs: [test-repository, semantic-commit]
    uses: Geode-solutions/actions/.github/workflows/dev-release.yml@master

  deploy-repository:
    needs: release
    uses: Geode-solutions/actions/.github/workflows/cpp-deploy-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repos: ${{ inputs.repos }}
      version: "0.0.0"
      release: ${{ github.head_ref }}-tag
      upload-pypi: false
      light: true
      python: ${{ inputs.python }}
    secrets: inherit
