on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      version:
        type: string
        required: true
      release:
        type: string
        required: true
      upload-pypi:
        type: boolean
        default: true
      branch:
        type: string
        default: ${{ github.ref }}
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  windows-python:
    runs-on: windows-2019
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: build/third_party
          key: ${{ runner.os }}-win64-${{ hashFiles('cmake/Configure**.cmake') }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - uses: Geode-solutions/actions/get-release@master
        id: repos
        with:
          repository: ${{ inputs.repos }}
          file: "win64-private.zip"
          token: ${{ secrets.TOKEN }}
          branch: ${{ inputs.branch }}
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
      - name: Compile
        run: |
          pip install wheel
          choco install openssl -r --no-progress
          if(!(test-path build)) { mkdir build }
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH:PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_TESTS:BOOL=OFF -DWHEEL_VERSION:STRING=${{ inputs.version }} -D${{ inputs.name }}_WITH_PYTHON:BOOL=ON -DPYTHON_VERSION:STRING=${{ matrix.python }} ..
          cmake --build .
          cd ${{ inputs.directory }}
          cmake --build . --target wheel
      - name: PyPI
        if: inputs.upload-pypi
        run: |
          pip install twine
          twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} --skip-existing --verbose build/${{ inputs.directory }}/wheel/dist/*.whl
      - name: Upload GH
        run: |
          Get-ChildItem -Path "build/${{ inputs.directory }}/wheel/dist" -Filter *.whl | Foreach-Object { gh release upload --clobber --repo ${env:GITHUB_REPOSITORY} ${{ inputs.release }} $_.FullName }
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Notify slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
