on:
  workflow_call:
    inputs:
      directory:
        type: string
        default: "."
      repos:
        type: string
      light:
        type: boolean
        default: false
      type:
        type: string
        default: "Debug"
      branch:
        type: string
        default: ${{ github.ref }}
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  linux:
    runs-on: ubuntu-latest
    container: ghcr.io/geode-solutions/${{ matrix.system }}:master
    strategy:
      matrix:
        system: ["ubuntu", "rhel"]
        exclude:
          - system: ${{ inputs.light && 'rhel' || 'dummy' }}
        include:
          - system: "ubuntu"
            cc: "clang"
            cxx: "clang++"
          - system: "rhel"
            cc: "gcc"
            cxx: "g++"
    env:
      CC: /usr/bin/${{ matrix.cc }}
      CXX: /usr/bin/${{ matrix.cxx }}
    steps:
      - name: Get info
        id: info
        run: |
          echo "name=${{ matrix.system }}" >> $GITHUB_OUTPUT
          if [ "${{ matrix.system }}" = "rhel" ]; then
            echo "lib=lib64" >> $GITHUB_OUTPUT
          else
            echo "lib=lib" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: actions/cache@v4
        with:
          path: build/third_party
          key: ${{ runner.os }}-${{ steps.info.outputs.name }}-${{ hashFiles('cmake/Configure**.cmake') }}
      - uses: Geode-solutions/actions/get-release@master
        id: repos
        with:
          repository: ${{ inputs.repos }}
          file: "-${{ steps.info.outputs.name }}-private.tar.gz"
          token: ${{ secrets.TOKEN }}
          branch: ${{ inputs.branch }}
      - name: Libraries
        id: libraries
        run: |
          new_path=$(echo "${{ steps.repos.outputs.path }}" | sed 's/\;/\/${{ steps.info.outputs.lib }}\:/g')
          echo "LD_LIBRARY_PATH=$new_path" >> $GITHUB_ENV
      - name: Compile
        run: |
          mkdir -p build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ inputs.type }} -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" ..
          cmake --build . -t third_party
          cd ${{ inputs.directory }}
          cmake --build . -t essential
          cmake --build . -t install
        env:
          GEODE_LICENSE_LOCATION: ${{ github.workspace }}/geode.lic
      - name: Test
        run: |
          rm -rf $GITHUB_WORKSPACE/build/${{ inputs.directory }}/bin
          mkdir -p test
          cd test
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ inputs.type }} -DCMAKE_PREFIX_PATH:PATH="${{ steps.repos.outputs.path }};$GITHUB_WORKSPACE/build/${{ inputs.directory }}/install;$GITHUB_WORKSPACE/build" ../tests
          cmake --build .
          ctest --output-on-failure --no-tests=error -j 2 -LE unstable
        env:
          GEODE_LICENSE_LOCATION: ${{ github.workspace }}/geode.lic
