on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      repo:
        type: string
        default: ${{ github.repository }}
    outputs:
      new_release:
        description: "Whether a new release was published"
        value: ${{ jobs.semantic-release.outputs.new_release }}
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  semantic-release:
    uses: Geode-solutions/actions/.github/workflows/release.yml@master
    secrets: inherit

  echo:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: ${{ needs.semantic-release.outputs.new_release }} == 'true'
    steps:
      - run: |
          echo ${{ needs }}
          echo ${{ needs.semantic-release }}
          echo ${{ needs.semantic-release.outputs }}

  deploy-repository:
    needs: semantic-release
    if: ${{ needs.semantic-release.outputs.new_release }} == 'true'
    uses: Geode-solutions/actions/.github/workflows/deploy-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repo: ${{ inputs.repo }}
      repos: ${{ inputs.repos }}
      version: ${{ needs.semantic-release.outputs.new_release_version }}
    secrets: inherit
