on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
      repo:
        type: string
        default: ${{ github.repository }}
    outputs:
      new_release:
        description: "Whether a new release was published"
        value: ${{ jobs.semantic-release.outputs.new_release }}
      new_version:
        description: "New release number"
        value: ${{ jobs.semantic-release.outputs.new_version }}
    secrets:
      TOKEN:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      PYPI_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.semantic.outputs.new_release_published }}
      new_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-repository:
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release == 'true'
    uses: Geode-solutions/actions/.github/workflows/deploy-repository.yml@master
    with:
      name: ${{ inputs.name }}
      directory: ${{ inputs.directory }}
      repo: ${{ inputs.repo }}
      repos: ${{ inputs.repos }}
      version: ${{ needs.semantic-release.outputs.new_version }}
    secrets: inherit
