on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      upload:
        type: boolean
        default: true
    secrets:
      TOKEN:
        required: true
      LICENSE_TOKEN:
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - name: GithubPackages Login
        if: inputs.upload
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Set IMAGE variable
        run: |
          repo=${GITHUB_REPOSITORY,,}
          echo $repo
          echo "IMAGE=ghcr.io/$repo:${{inputs.tag}}" >>${GITHUB_ENV}
      - name: Build Docker image
        run: |
          if [ "${{ secrets.LICENSE_TOKEN }}" != '' ]; then
            docker build -t $IMAGE --build-arg TOKEN=${{ secrets.LICENSE_TOKEN }} .
          else
            docker build -t $IMAGE .
          fi
      - name: Squash Docker image
        run: |
          pip install docker-squash
          docker-squash $IMAGE -t $IMAGE
      - name: Push Docker image to ghcr.io
        if: inputs.upload
        run: docker push $IMAGE
