on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      upload:
        type: boolean
        default: true
    secrets:
      TOKEN:
        required: true
      LICENSE_TOKEN:
        required: false

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
      - name: GithubPackages Login
        if: inputs.upload
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build docker
        uses: Geode-solutions/actions/build/docker@master
        id: docker
        with:
          tag: ${{ inputs.tag }}
          upload: ${{ inputs.upload }}
          license_token: ${{ secrets.LICENSE_TOKEN }}
      - name: Push Docker image to ghcr.io
        if: inputs.upload
        run: docker push ${{ steps.docker.outputs.image }}
