on: 
    workflow_call:
      inputs:
        image_name:
          type: string
          required: true
        tag:
          type: string
          required: true
      secrets:
        GITHUB_TOKEN:
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: True
    - name: GithubPackages Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build Docker image
      run: docker build --rm -f "Dockerfile" -t ghcr.io/geode-solutions/{{$image_name}}:{{$tag}} "."
    - name: Squash Docker image
      run: |
        pip install docker-squash
        docker-squash ghcr.io/{{$image_name}}:{{$tag}} -t ghcr.io/geode-solutions/{{$image_name}}:{{$tag}}
    - name: Push Docker image to ghcr.io
      run: docker push ghcr.io/geode-solutions/{{$image_name}}:{{$tag}}

    