on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      LICENSE_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{github.repository}}:${{inputs.tag}}
    steps:
      - uses: actions/checkout@v4
      - name: GithubPackages Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build Docker image
        run: |
          if [ "${{ secrets.LICENSE_TOKEN }}" != '' ]; then
            docker build -t $IMAGE --build-arg TOKEN=${{ secrets.LICENSE_TOKEN }} .
          else
            docker build -t $IMAGE .
          fi
      - name: Squash Docker image
        run: |
          pip install docker-squash
          docker-squash $IMAGE -t $IMAGE
      - name: Push Docker image to ghcr.io
        run: docker push $IMAGE
