on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      TOKEN:
        required: true
      LICENSE_TOKEN:
        required: false
      GOOGLE_CLOUD_KEY:
        required: true
      GOOGLE_CLOUD_PROJECT_ID:
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
      - name: GitHub Packages Login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west9-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CLOUD_KEY }}
      - name: Build docker
        uses: Geode-solutions/actions/build/docker@master
        id: docker
        with:
          tag: ${{ inputs.tag }}
          license_token: ${{ secrets.LICENSE_TOKEN }}
      - name: Push Docker image to ghcr.io
        run: docker push ${{ steps.docker.outputs.image }}
      - name: Tag and push to Google Artifact Registry
        run: |
          GAR_FULL_IMAGE="europe-west9-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}:${{ inputs.tag }}"
          echo "Tagging image for GAR: $GAR_FULL_IMAGE"
          docker tag ${{ steps.docker.outputs.image }} $GAR_FULL_IMAGE
          docker push $GAR_FULL_IMAGE