on: 
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tag:
        type: string
        required: true
      args:
        type: string
        required: false
    secrets:
      TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      IMAGE: ghcr.io/geode-solutions/${{inputs.image_name}}:${{inputs.tag}}
    steps:
    - uses: actions/checkout@v3
    - name: GithubPackages Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}
        
    - name: Build Docker image
      run: docker build -t $IMAGE --build-arg TOKEN=${{ secrets.TEST_TOKEN }} .
    - name: Squash Docker image
      run: |
        pip install docker-squash
        docker-squash $IMAGE -t $IMAGE
    - name: Push Docker image to ghcr.io
      run: docker push $IMAGE

    
