on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v4
      - name: "Get file config"
        run: |
          curl -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.clang-format\?ref\=master > .clang-format
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          extensions: 'hpp,cpp'
          clangFormatVersion: 19
          inplace: True
      - uses: stefanzweifel/git-auto-commit-action@v5
        id: commit
        with:
          commit_message: Apply format changes
      - name: "Run if changes have been detected"
        if: steps.commit.outputs.changes_detected == 'true'
        run: exit 1
