on: 
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        fetch-depth: 0
    - uses: Geode-solutions/actions/clang-format@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
