on: 
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
    - uses: DoozyX/clang-format-lint-action@v0
      with:
        extensions: 'h,cpp'
        clangFormatVersion: 14
        inplace: True
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply format changes
      
