on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  semantic-release:
    uses: Geode-solutions/actions/.github/workflows/release.yml@master
    with:
      dry_run: true
    secrets: inherit

  config:
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release == 'true'
    uses: Geode-solutions/actions/.github/workflows/js-config.yml@master
    secrets: inherit

  sleep:
    needs: config
    runs-on: ubuntu-latest
    steps:
      - name: Wait for registry to update
        run: sleep 1m

  prepare:
    needs: [config, sleep]
    uses: Geode-solutions/actions/.github/workflows/js-prepare.yml@master
    with:
      use_internal: true
    secrets: inherit
