on:
  workflow_call:
    inputs:
      repos:
        type: string
    secrets:
      TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: Geode-solutions/actions/.github/workflows/js-prepare.yml@master
    secrets: inherit

  oxlint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
      - uses: reviewdog/action-setup@v1
      - name: oxlint
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          echo "Base branch: $BASE_BRANCH"
          git fetch origin $BASE_BRANCH:$BASE_BRANCH --depth=1
          files=$(git diff --name-only $BASE_BRANCH ${{ github.sha }})
          npx oxlint --config .oxlintrc.json --format unix $files | reviewdog -efm="%f:%l:%c: %m [%r]" -reporter=github-pr-review -fail-level=any -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  config:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/js-config.yml@master
    secrets: inherit

  test-repository:
    needs: config
    uses: Geode-solutions/actions/.github/workflows/web-test-repository.yml@master
    with:
      repos: ${{ inputs.repos }}
      branch: ${{ github.event.pull_request.head.ref }}
      docker: false
      python: false
      node: ${{ needs.config.outputs.node }}
      integration: ${{ needs.config.outputs.integration }}
      browser: ${{ needs.config.outputs.browser }}
      desktop: ${{ needs.config.outputs.desktop }}
      microservices: ${{ needs.config.outputs.microservices }}
    secrets: inherit

  semantic-commit:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/semantic-commit.yml@master
    secrets: inherit

  release:
    needs: [test-repository, semantic-commit]
    uses: Geode-solutions/actions/.github/workflows/dev-release.yml@master

  deploy-repository:
    needs: [release, config]
    uses: Geode-solutions/actions/.github/workflows/web-deploy-repository.yml@master
    with:
      repos: ${{ inputs.repos }}
      branch: ${{ github.event.pull_request.head.ref }}
      version: "0.0.0"
      release: ${{ github.head_ref }}-tag
      release_channel: ${{ needs.release.outputs.new_release_channel }}
      upload: false
      python: false
      docker: false
      node: ${{ needs.config.outputs.node }}
      desktop: ${{ needs.config.outputs.desktop }}
    secrets: inherit
