on:
  workflow_call:
    inputs:
      repos:
        type: string
    secrets:
      TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: Geode-solutions/actions/.github/workflows/js-prepare.yml@master
    secrets: inherit

  oxlint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      # - uses: oxc-project/oxlint-action@v2.0.1
      #   with:
      #     config: .oxlintrc.json
      - uses: reviewdog/action-setup@v1
      - name: oxlint
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          echo "Base branch: $BASE_BRANCH"
          git fetch origin $BASE_BRANCH:$BASE_BRANCH --depth=1
          files=$(git diff --name-only $BASE_BRANCH ${{ github.sha }})
          npx oxlint --config .oxlintrc.json --format unix $files | reviewdog -efm="%f:%l:%c: %m [%t/%r]" -reporter=github-pr-review -fail-level=any
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-repository:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/web-test-repository.yml@master
    with:
      repos: ${{ inputs.repos }}
      branch: ${{ github.event.pull_request.head.ref }}
      docker: false
      python: false
      npm: true
    secrets: inherit

  semantic-commit:
    needs: prepare
    uses: Geode-solutions/actions/.github/workflows/semantic-commit.yml@master
    secrets: inherit

  release:
    needs: [test-repository, semantic-commit]
    uses: Geode-solutions/actions/.github/workflows/dev-release.yml@master

  deploy-repository:
    needs: release
    uses: Geode-solutions/actions/.github/workflows/web-deploy-repository.yml@master
    with:
      repos: ${{ inputs.repos }}
      branch: ${{ github.event.pull_request.head.ref }}
      version: "0.0.0"
      release: ${{ github.head_ref }}-tag
      release_channel: ${{ needs.release.outputs.new_release_channel }}
      upload: false
      python: false
      npm: true
      docker: false
    secrets: inherit
