on:
  workflow_call:
    inputs:
      # name:
      #   type: string
      #   required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
    secrets:
      TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:         
  prepare:
    uses: Geode-solutions/actions/.github/workflows/prepare.yml@master
    secrets: inherit
  
  check:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: build/third_party
          key: ${{ runner.os }}-ubuntu-${{ hashFiles('cmake/Configure**.cmake') }}
      - uses: Geode-solutions/actions/get-release@master
        id: repos
        with:
          repository: ${{ inputs.repos }}
          file: '-ubuntu-private.tar.gz'
          token: ${{ secrets.TOKEN }}
      - name: Configure
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" ..
          cmake --build . -t third_party -j 2
      - uses: ZedThree/clang-tidy-review@master
        with:
          build_dir: build/${{ inputs.directory }}
      - name: Sanitizers
        run: |
          cd build/${{ inputs.directory }}
          cmake -DUSE_SANITIZER_ADDRESS=ON -DUSE_SANITIZER_LEAK=ON -DUSE_SANITIZER_UNDEFINED_BEHAVIOR=ON .
          cmake --build . -j 2
          ctest -V -j 2
        env:
          GEODE_LICENSE_LOCATION: ${{ github.workspace }}/geode.lic
