on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    uses: Geode-solutions/actions/.github/workflows/py-prepare.yml@master
    secrets: inherit

  pylint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dciborow/action-pylint@main
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          glob_pattern: "**/*.py"
