on:
  workflow_call:
    inputs:
      repos:
        type: string
        required: true
      use_internal:
        type: boolean
        default: false
      branch:
        type: string
        default: ${{ github.ref_name }}
    outputs:
      changes_detected:
        description: "commit has been done"
        value: ${{ jobs.prepare.outputs.changes_detected }}
    secrets:
      TOKEN:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
          branch: ${{ inputs.branch }}
      - name: pip-compile
        uses: Geode-solutions/actions/install/pip-compile@master
        with:
          folders: .
          use_internal: ${{ inputs.use_internal }}
      - name: "Get config files"
        run: |
          curl -f --retry 3 --retry-delay 2 --retry-connrefused -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/commitlint.config.js\?ref\=master > commitlint.config.js
          curl -f --retry 3 --retry-delay 2 --retry-connrefused -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/.releaserc\?ref\=master > .releaserc
          curl -f --retry 3 --retry-delay 2 --retry-connrefused -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/mypy.ini\?ref\=master > mypy.ini
          curl -f --retry 3 --retry-delay 2 --retry-connrefused -H "Accept: application/vnd.github.VERSION.raw" -H "Authorization: token ${{ secrets.TOKEN }}" https://api.github.com/repos/Geode-solutions/actions/contents/ruff.toml\?ref\=master > ruff.toml
      - name: Ruff
        run: |
          pip install ruff
          ruff format .
      - name: Install dependencies
        if: hashFiles('package.json') != ''
        uses: Geode-solutions/actions/install/node-dependencies@master
        with:
          repos: ${{ inputs.repos }}
          branch: ${{ inputs.branch }}
          token: ${{ secrets.TOKEN }}
          use_registry: false
      - name: Json & Discard dependency install changes
        if: hashFiles('package.json') != ''
        run: |
          npm run json
          git checkout -- package.json
          rm -f -- ./*.tgz
      - uses: stefanzweifel/git-auto-commit-action@v7
        id: commit
        with:
          commit_message: Apply prepare changes
