on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:     
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release: ${{ steps.semantic.outputs.new_release_published }}
    steps:
    - uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      with:
        dry_run: true
    
  trigger:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release == 'true'
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'Geode-solutions',
              repo: 'Versions',
              workflow_id: 'deploy.yml',
              ref: 'master',
              inputs: { branch: 'next' }
            })