on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: "master"
    secrets:
      TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
          branch: ${{ inputs.branch }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          skip_dirty_check: true
          commit_message: "fix(Package): trigger new release"
          commit_options: "--allow-empty"
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'Geode-solutions',
              repo: 'Versions',
              workflow_id: 'deploy.yml',
              ref: 'master',
              inputs: { branch: '${{ inputs.branch }}' }
            })
