on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  semantic-release:
    uses: Geode-solutions/actions/.github/workflows/release.yml@master
    with:
      dry_run: true
    secrets: inherit

  trigger:
    runs-on: ubuntu-latest
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release == 'true'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'Geode-solutions',
              repo: 'Versions',
              workflow_id: 'deploy.yml',
              ref: 'master',
              inputs: { branch: 'next' }
            })
