on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: "master"

jobs:     
  release:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}
        ref: ${{ inputs.branch }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        skip_dirty_check: true
        commit_message: 'fix(Package): trigger new release'
        commit_options: '--allow-empty'