on: 
  workflow_call:
    inputs:
      directory:
        type: string
        default: "bindings/python"
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "pip-compile"
      run: |
        file=${{ inputs.directory }}/requirements.in
        if [ ! -f "$file" ]; then 
          exit 0
        fi
        pip install pip-tools
        pip-compile --upgrade $file
        sed -i -E 's/==(.+)\.(.+)\.(.+)/==\1\.*,>=\1\.\2\.\3/' ${{ inputs.directory }}/requirements.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: Apply pip upgrade
    - name: "Run if changes have been detected"
      if: steps.commit.outputs.changes_detected == 'true'
      run: exit 1
